### ISSUE TITLE
ember-resolver error when importing bootstrap v4 via bower 

### ISSUE THREAD

**Issue by gokatz** [ember-cli/ember-resolver#185]
When I'm trying to import the bootstrap V4 alpha 6 (Pre-Release) into my ember-cli-build file (app.import) via bower, the ember build throws an error Could not find module 'ember-resolver' imported from 'myapp/resolver'. But it works fine when importing v3. Any idea ???

I'm using 

- resolver: 2.0.3
- ember-cli: 2.10.0
- ember: 2.12.1 (ember-source)

**Comment by lpaulger** [comment]
Any update on this? I'm running into the same issue now with the latest ember-cli 2.15.1

"bootstrap": "4.0.0-beta"
"ember-cli": "~2.15.1"
"ember-resolver": "4.5.0"
"ember-source": "~2.15.0"

If I find a solution I'll be sure to post my findings here but any information would be awesome

**Comment by lpaulger** [comment]
I want to update that I managed to get my build passing with `boostrap@4.0.0-beta` and `ember-cli@2.15.1`. it ended up being that I had a jquery plugin (jquery-date-range-picker) because I wasn't using the proper ember package (ember-jquery-date-range-picker) and it wasn't installing dependencies correctly (moment)

once I started using the ember package it worked for me.

so @gokatz I assume your issue might be similiar

**Comment by stefanpenner** [comment]
We no longer support bower, if the problem exists outside of bower usage please feel to explain how/why and we can gladly reopen
